import {useState} from 'react';
import {FileText,Plus,Search,Trash2,LogOut,ArrowUpRight} from 'lucide-react';
import type {NoteSummary,User} from './cloud';
import type {DocumentData} from './document';
import {documentPath} from './routes';
type Props={user:User|null;notes:NoteSummary[];guest:DocumentData;working:boolean;open:(note:NoteSummary)=>void;create:()=>void;guestOpen:()=>void;login:()=>void;logout:()=>void;remove:(note:NoteSummary)=>void};
export function Home({user,notes,guest,working,open,create,guestOpen,login,logout,remove}:Props) {
  const [search,setSearch]=useState(''),[sort,setSort]=useState('recent');
  const filtered=notes.filter(n=>n.title.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'ko'):b.updatedAt-a.updatedAt);
  return <div className="library">
    <header className="library-header"><a href="/" className="brand"><span className="brand-symbol"><FileText size={22} strokeWidth={1.5}/></span><span className="wordmark">Paperdown</span></a><div className="library-account">{user?<><span className="account-avatar">{user.username[0].toUpperCase()}</span><span>{user.username}</span><button className="tool" aria-label="로그아웃" disabled={working} onClick={logout}><LogOut size={17}/></button></>:<button className="action-button" onClick={login}>로그인 / 회원가입</button>}</div></header>
    <main className="library-main">
      <section className="library-intro"><div><h1>생각을 담아두는 곳.</h1><p>{user?'한 장의 메모부터 긴 문서까지, 쓰던 자리에서 이어가세요.':'종이 위에 쓰듯 편집하고, 원하는 모습으로 남기세요.'}</p></div><button className="action-button primary" disabled={working} onClick={user?create:guestOpen}><Plus size={17}/>{user?'새 문서':'편집기 열기'}</button></section>
      <div className="library-toolbar"><h2>{user?'내 문서':'이 기기의 문서'}<span>{user?notes.length:1}</span></h2>{user&&<div className="library-tools"><label className="library-search"><Search size={16}/><input aria-label="문서 검색" placeholder="문서 찾기" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="library-sort" aria-label="문서 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">최근 수정순</option><option value="title">이름순</option></select></div>}</div>
      {user?<>{filtered.length?<div className="document-grid">{filtered.map(note=><article className="document-card" key={note.id}><a href={documentPath(note.id)} onClick={e=>{if(e.button===0&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();if(!working)open(note);}}} aria-label={`${note.title||'제목 없는 문서'} 열기`}><div className="document-cover"><FileText size={29} strokeWidth={1}/><span>{note.title||'제목 없는 문서'}</span></div><div className="document-card-info"><h3>{note.title||'제목 없는 문서'}</h3><p>{new Date(note.updatedAt).toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric'})} 수정</p></div></a><button className="document-card-delete tool" aria-label={`${note.title||'문서'} 삭제`} disabled={working} onClick={()=>remove(note)}><Trash2 size={15}/></button></article>)}</div>:<div className="library-empty"><FileText size={32} strokeWidth={1.2}/><h3>{search?'찾는 문서가 없습니다':'첫 문서를 만들어보세요'}</h3><p>{search?'다른 이름으로 검색해보세요.':'문서 이름과 내용은 쓰는 동안 자동으로 저장됩니다.'}</p>{!search&&<button className="action-button" disabled={working} onClick={create}><Plus size={16}/>새 문서 만들기</button>}</div>}</>:<div className="guest-library"><a className="guest-document" href={documentPath('local')} onClick={e=>{if(!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();guestOpen();}}}><FileText size={27} strokeWidth={1.2}/><div><h3>{guest.title||'제목 없는 문서'}</h3><p>이 브라우저에 저장된 문서 이어쓰기</p></div><ArrowUpRight size={19}/></a><div className="library-signin"><h3>문서를 한곳에 모아두세요.</h3><p>계정에 여러 문서를 저장하고 다른 기기에서도 이어 쓸 수 있습니다.</p><button className="action-button" onClick={login}>로그인 / 회원가입</button></div></div>}
      {user&&<a className="library-local" href={documentPath('local')} onClick={e=>{if(!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();guestOpen();}}}>이 기기에 저장된 문서 열기</a>}
    </main><footer className="library-footer"><span>Paperdown</span><span>글에 집중하고, 종이로 남기세요.</span></footer>
  </div>;
}
